### PR TITLE
Additions to Android manual set-up

### PR DESCRIPTION
**Pull request by Kenjirou**

### CODE REVIEW

**Comment by Kenjirou** [comment]
@mvayngrib sorry, can not assign you to this PR. Maybe you'll help me with that?

**Comment by mvayngrib** [comment]
@Kenjirou cool, thanks! Assigned myself. 

I think the two steps you added need to go in *both* Manual and Automatic installation, right?

**Comment by Kenjirou** [comment]
@mvayngrib yeah, you're right. I'll fix it.

**Comment by Kenjirou** [comment]
@mvayngrib done.
Also I've correct some markdown for multiline code to display it properly.

**Review by mvayngrib — APPROVED** [review]
looks good, thanks again!

**Pull request merged**
